### ISSUE TITLE
Deterministic builds are not possible

### ISSUE THREAD

**Issue by danwalmsley** [kekekeks/XamlX#17]
https://github.com/kekekeks/XamlX/blob/8d9fee734afaced9366774fda41b6aa2ab19875f/src/XamlX/Ast/Clr.cs#L643

This line causes random names everytime we compile...

We could probably sort alphabetically the xaml files,and use a counter that would produce the same names each time.

**Comment by CaasGit** [comment]
Was this closed by #19?
