### ISSUE TITLE
Unable to parse binding expression

### ISSUE THREAD

**Issue by danwalmsley** [kekekeks/XamlX#3]
`IsVisible="{Binding !$parent[cont|MetroWindow].DataContext.LockScreen.IsLocked}"`

gives a runtime error.

but:

`IsVisible="{Binding !$parent[Window].DataContext.LockScreen.IsLocked}"`

works

**Comment by kekekeks** [comment]
>gives a runtime error.

It's Avalonia issue then. Probably something related to the avalonia-specific runtime type resolver.
