### ISSUE TITLE
Cannot compile the project after deleting xaml and code behind files that were compiled before 

### ISSUE THREAD

**Issue by MarchingCube** [kekekeks/XamlX#37]
I've been seeing compile errors like this show up from time to time after deleting files/switching branches

>   Unable to find type `ControlCatalog.Pages.AcrylicPage` Line 1, position 2. [C:\Repositories\Avalonia\samples\ControlCatalog\ControlCatalog.csproj]
  AvaloniaBuildTasks.targets(94, 5): [MSB3073] The command "dotnet msbuild /nodereuse:false ControlCatalog.csproj /t:CompileAvaloniaXaml /p:_AvaloniaForceInternalMSBuild=true /p:Configuration=Debug /p:TargetFramework=netstandard2.0 /p:BuildProjectReferences=false" exited with code 1.

MSBuild log shows that resource generation task was skipped but xaml compilation was triggered again and is now complaining about having xaml without matching types.

> Build started 10/28/2020 10:41:36 PM.
Logging verbosity is set to: Normal.     1>Project "C:\Repositories\Avalonia\samples\ControlCatalog\ControlCatalog.csproj" on node 1 (build target(s)).
     1>GenerateAvaloniaResources:
       Skipping target "GenerateAvaloniaResources" because all output files are up-to-date with respect to the input files.
       GenerateTargetFrameworkMonikerAttribute:
       Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
       
I can easily repro this by:

1. Open Avalonia ControlCatalog project
2. Remove `AcrylicPage` from `MainView` (https://github.com/AvaloniaUI/Avalonia/blob/master/samples/ControlCatalog/MainView.xaml#L14)
3. Compile
4. Delete `AcrylicPage.xaml` and `AcrylicPage.xaml.cs` (I've used explorer)
5. Compile - it fails here

To make this compile again one has to change something in the project which generates correct resources.

**Comment by MarchingCube** [comment]
This fails both in Rider and VS so it is MSBuild related.

**Comment by kekekeks** [comment]
Fixed
