### ISSUE TITLE
Support for overriding Content attribute in derived classes

### ISSUE THREAD

**Issue by yevgeni-zolotko** [kekekeks/XamlX#45]
Hi, thank you for this library.
Consider the following situation:

```csharp
    class Base
    {
        [Content]
        public Base[] BaseProp { get; }
    }

    class Derived : Base
    {
        [Content]
        public Base[] DerivedProp { get; }
    }
```
With this code I would like to override the "content" property in `Derived` class to use `DerivedProp` instead of `BaseProp`.
Then when parsing the following XAML:

```xaml
    <Derived>
        <Base />
        <Base />
    </Derived>
```
I get error: `XamlX.XamlTypeSystemException: 'Content (or substitute) attribute is declared on multiple properties of Derived'`

Commenting the following code [here](https://github.com/kekekeks/XamlX/blob/9e90d34e97c766ba8dcb70128147fcded65d195a/src/XamlX/Transform/TransformerConfiguration.cs#L106):
```csharp
                if (GetCustomAttribute(p, TypeMappings.ContentAttributes).Any())
                {
                    //if (found != null && !p.Equals(found))
                    //    throw new XamlTypeSystemException(
                    //        "Content (or substitute) attribute is declared on multiple properties of " + type.GetFqn());
                    found = p;
                }
```
seems to solve this problem for me.

Maybe there is a different better way to achieve this? If not, should we cover this case in the library? I can submit a PR if needed.

**Comment by yll690** [comment]
I also want this feature. It seems simple. Is there other considerations? @kekekeks
