### ISSUE TITLE
Emit DynamicDependency for CompiledAvaloniaXaml types to prevent compiled xaml from trimming

### ISSUE THREAD

**Issue by hez2010** [kekekeks/XamlX#61]
Emit `DynamicDependency` for `CompiledAvaloniaXaml.*` on program entry point to prevent from trimming when compile against net5.0+.

For example,
```csharp
[DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(CompiledAvaloniaXaml.!AvaloniaResources))]
[DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(CompiledAvaloniaXaml.!EmbeddedResource))]
[DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(CompiledAvaloniaXaml.!IndexerAccessorFactoryClosure))]
[DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(CompiledAvaloniaXaml.!XamlLoader))]
[DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(CompiledAvaloniaXaml.XamlIlContext))]
[DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(CompiledAvaloniaXaml.XamlIlHelpers))]
[DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(CompiledAvaloniaXaml.XamlIlTrampolines))]
static void Main() // or other method which is directly referenced in code path
{
    // ...
}
```

This can ensure compiled avalonia xaml types and members won't be trimmed by ILLinker even with `/p:TrimmerDefaultAction=true`.

**Comment by kekekeks** [comment]
We should just fix StyleInclude/ResourceInclude so they would directly reference the code instead of using reflection. It was left as "something to fix later" and it's been 3 years already -_-

**Comment by hez2010** [comment]
I think before the reflection-free approach got implemented, putting abose trimming attributes on an empty module initializer is a helpful workaround.

**Comment by maxkatz6** [comment]
StyleInclude/ResourceInclude were fixed to work without reflection (with some remaining bugs, but I am working on it).
So, this can be closed now.

**Comment by maxkatz6** [comment]
Ah, that's a XamlX repository. Either way, `CompiledAvaloniaXaml` type was emitted by the Avalonia XAML extensions, and not by the XamlX itself. So same problem isn't actually related to the XamlX by itself.
