### ISSUE TITLE
x:Static with "Path"

### ISSUE THREAD

**Issue by topeterk** [kekekeks/XamlX#68]
Hi, not sure if this is intended or a limitation of not being able to give a path to an x:Static statement?

Here an example what I try to use:
``` xaml
<DataTriggerBehavior Binding="{Binding Action}"
                     ComparisonCondition="Equal"
                     Value="{x:Static local:ProfileActionPageViewModel.ProfileAction.Delete}">
    <ChangePropertyAction TargetObject="{Binding $parent[TextBlock]}"
                          PropertyName="Text"
                          Value="Deleting a profile..." />
</DataTriggerBehavior>
```

Since `local:ProfileActionPageViewModel.ProfileAction.Delete` does not work, I only got it working when I moved the enum definition out of the class scope into the namespace scope and reference it like so `local:ProfileAction.Delete`.

Is this a limitation of x:Static or is this a bug (not yet implemented feature)?
Or am I doing anything wrong?

PS: produced error:  
`ProfileActionPage.xaml(46,93,46,93): Avalonia error XAMLIL: Unable to resolve ProfileAction.Create as static field, property, constant or enum value Zeile 46, Position 93.`

**Comment by maxkatz6** [comment]
This PR should solve it
https://github.com/kekekeks/XamlX/pull/54
But from what I remember there was some blocker with it...

**Comment by topeterk** [comment]
Ah "nested" was the word that I was looking for in order to check for already opened issues but it didn't wanted to come into my mind :)

On my Xamarin project I used the notation with the plus sign `local:ProfileActionPageViewModel+ProfileAction.Delete` which would also solve my issue when this support gets integrated. So, I do not need an support for any "Path" like it is available for Bindings. Therefore we can close this issue here and I will follow the mentioned PR. Thanks
