### ISSUE TITLE
Svelte and Xaml ❓ 

### ISSUE THREAD

**Issue by ByEBA** [kekekeks/XamlX#76]
Hello,
I've been interested in svelte for a while. I also found avalonia for desktop programming. As a result of my research, I realized that axaml is an extension that belongs to this repository. While asking myself why a different xaml engine is needed. I found out that xamlx engine compiles IL code on ast. The same logic is valid in svelte, the room generates pure javascript file through ast code.
I wonder if I can generate xaml using xamlx and svelte?

[Svelte Compiler](https://svelte.dev/docs#compile-time-svelte-compile)

Converting xaml using javascript is a silly idea, of course, but I'm asking because I'm curious. Excuse me for my ignorance.

**Comment by kekekeks** [comment]
I think the main problem would be the difference between XAML language and javascript component is that XAML is _completely declarative_. You can't have imperative code in a xaml file, it's just some instructions of how to assemble an object tree. 
React, Angular, Vue, Svelte and others _rely_ on having inline JavaScript. So such components can't be converted to XAML.

XAML is also supposed to be used with MVVM paradigm.

**Comment by ByEBA** [comment]
Thank you for the answer. It was enlightening for me.
