### ISSUE TITLE
[Question] Serializze AST

### ISSUE THREAD

**Issue by workgroupengineering** [kekekeks/XamlX#97]
Do you have any examples of how to sterilize the AST? I tried with System.Text.Json but I get empty files.

**Comment by workgroupengineering** [comment]
Any suggestions?

I was thinking of creating a class that takes advantage of the Visitor pattern. Do you think it could work?

I would like to use the AST inside `AvaloniaVS` instead of `Avalonia.Ide.CompletionEngine` but keep the decoupling from the Avalonia version.

Using the ASTA in Avalonia VS would allow you to make the Itellisense more intelligent with:

- fine the identification : the resources, styles and name of controls
- creation of editors like the color, transformations etc..
- populate Properties Window.
- etc

**Comment by kekekeks** [comment]
Avalonia.Ide.CompletionEngine is supposed to be reusable between VS extension and VSCode extension. AvaloniaVS is supposed to **only** provide the glue between the engine and the IDE. So ideally the code has to be structured in a way that could be reused by a different IDE.

**Comment by kekekeks** [comment]
As of serialization, I think JSON.NET supports cyclic references.

**Comment by workgroupengineering** [comment]
> As of serialization, I think JSON.NET supports cyclic references.

I already tried but tried, but it gives me OutOfMemoryException.

> Avalonia.Ide.CompletionEngine is supposed to be reusable between VS extension and VSCode extension. AvaloniaVS is supposed to **only** provide the glue between the engine and the IDE. So ideally the code has to be structured in a way that could be reused by a different IDE.

The idea is to implement an LSP so that the logic can be shared with all IDEs that support this standard.

**Comment by kekekeks** [comment]
1) `new JsonSerializerSettings { PreserveReferencesHandling = PreserveReferencesHandling.Objects }`
2) special converters for types from IXamlTypeSystem
